# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q4W5Mf2jtRbuUHejAVtFCT7enkXEDNbL
"""

!pip install ultralytics

from ultralytics import YOLO

# Load YOLOv10n model from scratch
model = YOLO("yolov10b.yaml")

# Train the model
model.train(data="/content/yolo/data.yaml", epochs=100, imgsz=640)

import zipfile
import os

# 指定要解壓縮的 ZIP 檔案
zip_file_path = '/content/Safety Inspection.v4i.yolov8.zip'

# 指定解壓縮的目標資料夾
extract_to_folder = '/content'

# 檢查 ZIP 檔案是否存在
if zipfile.is_zipfile(zip_file_path):
    # 打開 ZIP 檔案
    with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
        # 解壓縮所有內容到目標資料夾
        zip_ref.extractall(extract_to_folder)
        print(f"檔案已解壓縮至 {extract_to_folder}")
else:
    print("這不是一個有效的 ZIP 檔案")